### PR TITLE
upgrade typescript, use composite, remove require usage (76  0️⃣ )

### PR DESCRIPTION
**Pull request by bollwyvl**
> This can wait for review until after the next release, but will be the starting point for some additional PRs.

To simplify the changes in step 1 of #76, this prepares things a bit, such that the move into `packages` will be straight moves, rather than move-and-changes.

Concretely:
- [x] upgrades typescript to what lab is currently using 
  - [x] resolve `yarn.lock`
  - [x] appeases some `empty block` lint fails
- [x] cleans up some imports (use of `require`, re-exporting of CodeMirror in a few places)
- [x] add `composite: true`
- [x] adds the `-b` flag to `build` and `watch`

### CODE REVIEW

**Comment by bollwyvl** [comment]
One windows flake, but otherwise good!

**Comment by krassowski** [comment]
Okay, the manual Azure Pipelines restart does not work due to https://developercommunity.visualstudio.com/content/problem/784369/rerun-failed-jobs-transitions-task-to-canceled.html.

**Comment by bollwyvl** [comment]
Yeah. Bummer. Can you "enqueue new build"? I don't have perms (which is
fine! More looking for more chores) It might not get picked up in gh,
though....

**Comment by krassowski** [comment]
It went through smoothly at https://dev.azure.com/krassowskimichal/jupyterlab-lsp/_build/results?buildId=84&view=logs&j=a1481901-c0b1-5ce5-074c-5d9d313a786f. I reviewed this step [0] (no comments) and I'm going to merge it now so we have this in before the presentation.

I am not sure if I want to merge step [1] already or first finish off other PRs and then merge it.
I will take a closer look tonight.

**Pull request merged**
