### PR TITLE
Release 3.3.0 and 1.1.2

### PR DESCRIPTION
**Pull request by krassowski**
Release time :tada:

Also enabling CI builds on 2.x.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Probably want to delete this branch before cutting the release...

**Comment by krassowski** [comment]
Is it the tag with the same name as the branch that causes problem?

**Comment by krassowski** [comment]
I see that this might be not convenient: https://softwareengineering.stackexchange.com/questions/230438/in-git-is-it-a-bad-idea-to-create-a-tag-with-the-same-name-as-a-deleted-branch. Is there a release branch naming scheme that you would prefer to avoid clashes?

**Comment by bollwyvl** [comment]
Yeah, to git, it's all just `refs`... having almost-the-same-named branches and tags can lead to ... problems. I think we're well and down the _tags start with `v`_ line at this point... no need to change anything...

**Comment by bollwyvl** [comment]
https://github.com/conda-forge/jupyter-lsp-feedstock/pull/15

**Pull request merged**
