### PR TITLE
Add an empty properties to settings schema

### PR DESCRIPTION
**Pull request by bollwyvl**
Even though we don't have any settings to configure, we need an empty `properties` so that the settings editor can draw it without failing (and mucking up the UI).

Will also add a test...

### CODE REVIEW

**Comment by bollwyvl** [comment]
Still flaking on conda... needs #72

**Comment by bollwyvl** [comment]
Well, #72 helped, but still getting some flake (windows R and JSX or something).

I think we need the status/feature indicator, e.g. https://github.com/krassowski/jupyterlab-lsp/issues/61#issuecomment-542370182, to give us something concrete to wait on. This will get especially important for diagnostics, as they can take a _very_ long time if they actually resolve references.

**Comment by bollwyvl** [comment]
We should probably get this in before the next npm release... The
almost-empty settings page looks pretty boring, but breaking the settings
page is pretty bad.

**Comment by krassowski** [comment]
Oh, I get it now (could not understand what was the problem so set it aside for now). Thanks for the additional info. Merging.

**Comment by bollwyvl** [comment]
Hooray!

**Pull request merged**
