### PR TITLE
Backport #474 to 2.x

### PR DESCRIPTION
**Pull request by jtpio**
## References

This is a backport of the fix from https://github.com/krassowski/jupyterlab-lsp/pull/474 to the `2.x` branch.

## Chores

- [ ] linted
- [ ] tested
- [ ] documented
- [ ] changelog entry

### CODE REVIEW

**Comment by krassowski** [comment]
Thanks! Do you need any other back-ports for 2.x?

**Comment by jtpio** [comment]
Thanks!

> Do you need any other back-ports for 2.x?

I think only this one. Thanks again for the fix!

**Comment by jtpio** [comment]
btw @krassowski, happy to help cutting a release with this fix.

For the 2.x, packages, I guess only pushing to `npm` is required?

**Comment by SylvainCorlay** [comment]
A release of the 2.x package would be fantastic!

**Comment by krassowski** [comment]
I ran out of open source time last weekend, will look into it tomorrow.

**Comment by krassowski** [comment]
Now released on npm. Please let me know of any issues. Hope it helps!

**Comment by jtpio** [comment]
Thanks!

**Pull request merged**
