### PR TITLE
Add readthedocs configuration, docs updates

### LINKED ISSUE #216: Publish docs on readthedocs
## Elevator Pitch

Publish the built docs on Read the Docs.

## Motivation

The current state of the docs is _meant_ to be built and published, but it just isn't yet. Even if we can't get everything they offer working, it's better than where we are: #211.

## Design Ideas

I'll do a test setup in a temporary project, get it working, and then we can make a new one that won't have all the "fix this, fix that" commits/builds, and hopefully it will work the first tiem.

Of late I've been running into more limitations when using conda there, which might limit the approach of "only document what works"... and their apt-provided nodejs (8) has been EOLed. Basically I've been using the (also old, but not compatible with our deps) nodejs from anaconda, and then doing everything with pip, but all of the r stuff is _right_ out.

So we might have to cheat, a bit, to get the data out without the servers actually _working_: definitely better to have the docs generated from the code that we test than to maintain it in both places, the whole motivation behind only checking in sources.

### PR DESCRIPTION
**Pull request by bollwyvl**
# [Preview](https://jlsptest.readthedocs.io)

> i'll delete that project once we're up and running

## References

- fixes #216
- might fix some of the other docs issues, but then again, maybe not

## Code changes

- [x] add `readthedocs.yml`
- [x] add `docs/rtd.yml`, a special env just for some limitations there (can't use conda-forge, basically)
- [x] add version checking of `Installation.ipynb`
- [x] add `JUPYTER_LSP_BUILDING_DOCS` environment variable to disable all of the checks for servers we won't be able to install in rtd

## Not in the PR
- [ ] set up real readthedocs project
  - don't forget the env var!
- [ ] add link to readme (once it's up)
- [ ] change in-lab link to point to readthedocs 
- [ ] decide how to manage `latest`, `stable`, etc.

## User-facing changes

- [x] updates some docs to consistently use `jupyter-lsp` (vs `jupyter_lsp`)
- [x] fix some versions
- [x] fix some package names

## Backwards-incompatible changes

- none

## Chores

- [x] linted
- [x] tested (still haven't locally reproduced #214)
- [x] documented (ha!)
- [ ] changelog entry (don't think it needs it, yet)

### CODE REVIEW

**Comment by bollwyvl** [comment]
Probably done for the day, but will take a look at the CI fails this weekend.

**Comment by krassowski** [comment]
Thank you. Merging as is.

**Comment by krassowski** [comment]
@bollwyvl will you be setting up the prod version, or should I take it from here? For domain, I would use jupyterlab-lsp to match the repo name.

**Comment by bollwyvl** [comment]
Your call either way. It'll be a bit before I can get to it!

**Comment by bollwyvl** [comment]
I see you got the docs up, hooray! I'll take a dive into our pyls issues...

**Pull request merged**
