### PR TITLE
Fix highlighting in hover tooltips and start testing the hover feature

### PR DESCRIPTION
**Pull request by krassowski**
## References

A step towards #297

## Code changes

- Fixed missing new lines in markdown generation which were causing the code in the tooltips to be rendered without syntax highlighting
- Added setting for hover tooltip debouncer.
- Removed unneeded margin/padding on the bottom and right side of the tooltip
- Added `className` option to the custom tooltip subclass
- Added tests for hover in notebooks; they check that the syntax highlighting is correctly applied
- Fix the underline
- Improve multi-element hover display (deprecated API)

## User-facing changes

| before | after |
|--------|-------|
| before_lsp   |  after_hover   |

Final:
hover

## Backwards-incompatible changes

None

## Chores

- [x] linted
- [x] tested
- [ ] documented
- [x] changelog entry

### CODE REVIEW

**Comment by krassowski** [comment]
Actually, we used to get these nice underlines indicating whether hover is available or not. This seems to be broken in 2.0.

**Comment by krassowski** [comment]
Underlines are now fixed; the only remaining problem is with tests, as the improved implementation does not allow to work it around easily. Will need to implement the delay-based hover for tests...

**Comment by krassowski** [comment]
@bollwyvl, how would you approach the action chains issue? There is https://github.com/hmalphettes/robotframework-selenium2library-extensions but it was not updated in ages nor released. We could try to extend SeleniumLibrary https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/extending.rst (lot's of reading it seems, no time at the moment..)

**Comment by bollwyvl** [comment]
Sorry, didn't have a chance to dig into this yet, nor have I been able to
find my old code.

I'd probably make a quick and dirty library that used raw selenium stuff,
e.g. hover_with_modifier(selector, modifier=None) and hide the action chain
stuff in there. We should not take that library you mention as a
dependency, it's caused me issues in the past.

Speaking if freaky dependencies: I have also been looking into:

https://github.com/MarketSquare/robotframework-browser

...which uses the nodejs-based playwright, which theoretically supports
more browsers, though with less control, with more rando binary blobs.

Anyhow, its "Hover" keyword already accepts modifiers:

*https://marketsquare.github.io/robotframework-browser/Browser.html#Hover
<https://marketsquare.github.io/robotframework-browser/Browser.html#Hover>*

I'll be trying it out on some greenfield stuff, and if it's useful, looking
into packaging it, yadda yadda.

**Pull request merged**
