### PR TITLE
Add config for the classic notebook server extension

### LINKED ISSUE #503: JupyterLab 3 support using repo2docker / binder
`jupyterlab-lsp` is great and I am trying to use it with the new JupyterLab 3.

I tried to build a binder ready project (see below the configuration files) it looks like I still had to do in the postBuild
```shell
jupyter serverextension enable --py jupyter_lsp  --sys-prefix
```

Is this as expected?

----

- `environment.yml` file:

```yaml
channels:
  - conda-forge

dependencies:
  - python >=3.6,<3.9.0a0
  - jupyterlab >=3.0.0,<4.0.0a0
  - jupyter-offlinenotebook >=0.2
  - jupyterlab-lsp=3.3.0
  - jupyter-lsp-python=1.1.2
```

- `postBuild` file:
```shell
set -e

jupyter serverextension enable --py jupyter_lsp  --sys-prefix
```

### PR DESCRIPTION
**Pull request by jtpio**
## References

Fixes #503 

## Code changes

Add the config file to enable the server extension for the classic notebook server.

## User-facing changes

Users using JupyterLab as a classic notebook server extension won't need the additional `jupyter serverextension enable` step.

## Backwards-incompatible changes

None

## Chores

- [x] linted
- [x] tested
- [ ] documented
- [x] changelog entry

### CODE REVIEW

**Review by bollwyvl — APPROVED** [review]
lgtm, thanks so much

**Comment by jtpio** [comment]
Not sure if this needs a changelog entry? (probably yes)

Do you already know the next version, or mark as `unreleased` for now?

**Comment by bollwyvl** [comment]
I don't know what the next planned release is. This seems like a useful point release, as it's biting people, but @krassowski has been handling the releases. Thanks!

**Comment by krassowski** [comment]
It will be 3.3.1 or 3.4.0 depending on how much time I will find this weekend and whether I will introduce new features or only bug fixes. I tend to start with naming it a point release: `3.3.1 (unreleased)` and then changing if needed on the flight.

**Comment by krassowski** [comment]
Oh, sorry, this will be jupyter-lsp not jupyterlab-lsp. So this will be a point release definitely. `1.1.3` I think.

**Comment by jtpio** [comment]
> `1.1.3` I think.

ok I'll add this to the changelog then.

**Comment by krassowski** [comment]
Thank you!

**Pull request merged**
