### PR TITLE
completion case sensitive will  keep a no need token value

### PR DESCRIPTION
**Pull request by yunair**
## Code changes

There has two changes.

All in `completion.ts`.

1.  change `merge_replies` function.
when `lsp.start > kernel.start`, correct the right prefix. 
`kernel.start` is the wrong index, because this index is merge all content in cell, and calculate the index, not the current line index.

2.  change `hint` function.

if check text startsWith token case sensitive,
It will keep a no need token value.

Input `from time import T`
before after completion, there will be `from time import Ttime`
now, there will be `from time import time`

## Chores

- [x] linted
- [x] tested
- [x] changelog entry

### CODE REVIEW

**Comment by krassowski** [comment]
Thank you, your contributions are very welcome. I see that these changes might be a step in the right direction, but we will need tests for this before I merge it.

I will be preparing basic browser tests for features of interests soon and let you know here.

**Comment by krassowski** [comment]
Many thanks again for the fix @yunair. Please have a look at the tests that I added here and feel encouraged to include such tests yourself for the future PRs!

**Comment by krassowski** [comment]
This improves #30 (but does not solve it, especially not for R where tokens are more tricky with all the dots everywhere).

**Comment by yunair** [comment]
Ok, I'll add such tests for the future PRs in this situation

**Pull request merged**
