### PR TITLE
try mamba, remove docs job in azure

### PR DESCRIPTION
**Pull request by bollwyvl**
## References

- attempt at https://github.com/krassowski/jupyterlab-lsp/issues/311#issuecomment-671661109

## Code changes

- updates and uses `mamba` instead of `conda`
- removes docs jobs (because RTD)

## User-facing changes

- n/a

## Backwards-incompatible changes

- n/a

## Chores

- [ ] linted
- [ ] tested
- [ ] documented
  - not sure if we'll want to also _recommend_ this, since we _use_ it? 
- [ ] changelog entry

### CODE REVIEW

**Comment by bollwyvl** [comment]
| before | after |
|----|----|
| Screenshot_2020-08-10 Pipelines - Run 20200811 2 logs  | Screenshot_2020-08-10 Pipelines - Run 20200811 3 logs

**Comment by bollwyvl** [comment]
Hah, windows still failing, will try pinning conda (looks line conda-forge maybe jumped the gun with 4.8.4)

**Comment by bollwyvl** [comment]
| before | after |
|------|-------|
| Screenshot_2020-08-10 Pipelines - Run 20200811 2 logs(2) | Screenshot_2020-08-10 Pipelines - Run 20200811 3 logs(1) |

yeah, so looks like a minute across the board (still-running job flaked).  Not bad! I've tried pinning conda, and telling it not to update incidental packages, will see if that offsets the additional expense of mamba and friends (or makes it worse).

**Comment by bollwyvl** [comment]
Still fail on windows, but got further. interesting that our huge solve actually went slower, but there's so many factors...

| before | after |
|-|-|
| Screenshot_2020-08-11 Pipelines - Run 20200811 2 logs | Screenshot_2020-08-11 Pipelines - Run 20200811 4 logs |

**Comment by bollwyvl** [comment]
The tea laves (win/36) suggest we're saving a couple minutes on windows, which makes sense. So we can either:
- merge this now, just rely on those gains for future stuff
- see how some other approaches (like conda-lock) work, in isolation (as it would become less reliant on runtime solves)

| before | after |
|-|-|
| Screenshot_2020-08-11 Pipelines - Run 20200811 2 logs(1) | Screenshot_2020-08-11 Pipelines - Run 20200811 5 logs

**Comment by krassowski** [comment]
Yes, this seems like a step in the right direction. Feel free to merge or explore other options! I do have high hopes for GitHub Actions.

**Comment by bollwyvl** [comment]
Welp, it's easy to back out, and making subsequent experimentation _faster_ is just, well, _faster_!

**Pull request merged**
